language: python
jobs:
  include:
    - stage:
      python: 3.6
      env: TOXENV=flake8
    - stage:
      python: 2.7
    - stage:
      python: 3.6
    - stage:
      python: pypy
    - stage:
      python: pypy3
    - stage: deploy
      python: 3.6
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: davehunt
        password:
        distributions: sdist bdist_wheel
        on:
          tags: true
          repo: davehunt/pytest-fxa
cache:
  pip: true
install: pip install tox-travis
script: tox
